import { BaseAgent, BaseAgentConfig, AgentCommandConfig } from "./base";
import { ModelConfig } from "./utils";
import {
  AgentType,
  GrokConfig,
  GrokResponse,
  GrokStreamCallbacks,
  Conversation,
  ModelProvider,
} from "../types";

export class GrokAgent extends BaseAgent {
  private grokApiKey: string;
  private model?: string;
  private baseUrl?: string;

  private escapePrompt(prompt: string): string {
    // Escape backticks and other special characters
    return prompt.replace(/[`"$\\]/g, "\\$&");
  }

  constructor(config: GrokConfig) {
    const baseConfig: BaseAgentConfig = {
      githubToken: config.githubToken,
      repoUrl: config.repoUrl,
      sandboxProvider: config.sandboxProvider,
      secrets: config.secrets,
      sandboxId: config.sandboxId,
      telemetry: config.telemetry,
      workingDirectory: config.workingDirectory,
      localMCP: config.localMCP,
    };

    super(baseConfig);

    // Validate that provider is xai if specified (Grok only supports xai)
    if (config.provider && config.provider !== "xai") {
      throw new Error("Grok agent only supports 'xai' provider");
    }

    // Store config values
    const envApiKey = process.env.GROK_API_KEY || process.env.XAI_API_KEY;
    const apiKey = config.providerApiKey || envApiKey;
    
    if (!apiKey) {
      throw new Error(
        "Grok agent requires providerApiKey or GROK_API_KEY environment variable"
      );
    }
    
    this.grokApiKey = apiKey;
    this.model = config.model;
    this.baseUrl = config.baseUrl;
  }

  protected getCommandConfig(
    prompt: string,
    mode?: "ask" | "code"
  ): AgentCommandConfig {
    let instruction: string;
    if (mode === "ask") {
      instruction =
        "Research the repository and answer the user's questions. " +
        "Do NOT make any changes to any files in the repository.";
    } else {
      instruction =
        "Do the necessary changes to the codebase based on the users input.\n" +
        "Don't ask any follow up questions.";
    }

    const escapedPrompt = this.escapePrompt(prompt);
    const modelFlag = this.model ? `--model ${this.model}` : "";
    const baseUrlFlag = this.baseUrl ? `--base-url ${this.baseUrl}` : "";

    return {
      command: `echo "${escapedPrompt}" | grok ${modelFlag} ${baseUrlFlag} --prompt "${instruction}"`,
      errorPrefix: "Grok",
      labelName: "grok",
      labelColor: "00D4AA",
      labelDescription: "Generated by Grok AI agent",
    };
  }

  protected getDefaultTemplate(): string {
    return "vibekit-grok";
  }

  protected getEnvironmentVariables(): Record<string, string> {
    const envVars: Record<string, string> = {
      GROK_API_KEY: this.grokApiKey,
    };

    if (this.baseUrl) {
      envVars.GROK_BASE_URL = this.baseUrl;
    }

    return envVars;
  }

  protected getApiKey(): string {
    return this.grokApiKey;
  }

  protected getAgentType(): AgentType {
    return "grok";
  }

  protected getModelConfig(): ModelConfig {
    return {
      provider: "xai",
      apiKey: this.grokApiKey,
      model: this.model,
      baseUrl: this.baseUrl,
    };
  }

  // Override generateCode to support history in the instruction
  public async generateCode(
    prompt: string,
    mode?: "ask" | "code",
    branch?: string,
    history?: Conversation[],
    callbacks?: GrokStreamCallbacks,
    background?: boolean
  ): Promise<GrokResponse> {
    let instruction: string;
    if (mode === "ask") {
      instruction =
        "Research the repository and answer the user's questions. " +
        "Do NOT make any changes to any files in the repository.";
    } else {
      instruction =
        "Do the necessary changes to the codebase based on the users input.\n" +
        "Don't ask any follow up questions.";
    }

    if (history && history.length > 0) {
      instruction += `\n\nConversation history: ${history
        .map((h) => `${h.role}\n ${h.content}`)
        .join("\n\n")}`;
    }

    const escapedPrompt = this.escapePrompt(prompt);
    const modelFlag = this.model ? `--model ${this.model}` : "";
    const baseUrlFlag = this.baseUrl ? `--base-url ${this.baseUrl}` : "";

    // Override the command config with history-aware instruction
    const originalGetCommandConfig = this.getCommandConfig.bind(this);
    this.getCommandConfig = (p: string, m?: "ask" | "code") => ({
      ...originalGetCommandConfig(p, m),
      command: `echo "${escapedPrompt}" | grok ${modelFlag} ${baseUrlFlag} --prompt "${instruction}"`,
    });

    const result = await super.generateCode(
      prompt,
      mode,
      branch,
      history,
      callbacks,
      background
    );

    // Restore original method
    this.getCommandConfig = originalGetCommandConfig;

    return result as GrokResponse;
  }
}