import { BaseAgent, BaseAgentConfig, AgentCommandConfig } from "./base";
import {
  ClaudeConfig,
  ClaudeResponse,
  ClaudeStreamCallbacks,
  Conversation,
} from "../types";

export class ClaudeAgent extends BaseAgent {
  private anthropicApiKey: string;

  constructor(config: ClaudeConfig) {
    const baseConfig: BaseAgentConfig = {
      githubToken: config.githubToken,
      repoUrl: config.repoUrl,
      e2bApiKey: config.e2bApiKey,
      e2bTemplateId: config.e2bTemplateId,
      sandboxId: config.sandboxId,
      telemetry: config.telemetry,
    };

    super(baseConfig);
    this.anthropicApiKey = config.anthropicApiKey;
  }

  protected getCommandConfig(
    prompt: string,
    mode?: "ask" | "code"
  ): AgentCommandConfig {
    let instruction: string;
    if (mode === "ask") {
      instruction =
        "Research the repository and answer the user's questions. " +
        "Do NOT make any changes to any files in the repository.";
    } else {
      instruction =
        "Do the necessary changes to the codebase based on the users input.\n" +
        "Don't ask any follow up questions.";
    }

    return {
      command: `echo "${prompt}" | claude -p --append-system-prompt "${instruction}"${
        mode === "ask" ? ' --disallowedTools "Edit" "Replace" "Write"' : ""
      } --output-format stream-json --verbose`,
      errorPrefix: "Claude",
      labelName: "claude",
      labelColor: "FF6B35",
      labelDescription: "Generated by Claude AI agent",
    };
  }

  protected getDefaultTemplate(): string {
    return "vibekit-claude";
  }

  protected getEnvironmentVariables(): Record<string, string> {
    return {
      ANTHROPIC_API_KEY: this.anthropicApiKey,
    };
  }

  protected getApiKey(): string {
    return this.anthropicApiKey;
  }

  protected getAgentType(): "codex" | "claude" {
    return "claude";
  }

  // Override generateCode to support history in the instruction
  public async generateCode(
    prompt: string,
    mode?: "ask" | "code",
    history?: Conversation[],
    callbacks?: ClaudeStreamCallbacks
  ): Promise<ClaudeResponse> {
    let instruction: string;
    if (mode === "ask") {
      instruction =
        "Research the repository and answer the user's questions. " +
        "Do NOT make any changes to any files in the repository.";
    } else {
      instruction =
        "Do the necessary changes to the codebase based on the users input.\n" +
        "Don't ask any follow up questions.";
    }

    if (history && history.length > 0) {
      instruction += `\n\nConversation history: ${history
        .map((h) => `${h.role}\n ${h.content}`)
        .join("\n\n")}`;
    }

    // Override the command config with history-aware instruction
    const originalGetCommandConfig = this.getCommandConfig.bind(this);
    this.getCommandConfig = (p: string, m?: "ask" | "code") => ({
      ...originalGetCommandConfig(p, m),
      command: `echo "${prompt}" | claude -p --append-system-prompt "${instruction}"${
        mode === "ask" ? ' --disallowedTools "Edit" "Replace" "Write"' : ""
      } --output-format stream-json --verbose --dangerously-skip-permissions`,
    });

    const result = await super.generateCode(prompt, mode, history, callbacks);

    // Restore original method
    this.getCommandConfig = originalGetCommandConfig;

    return result as ClaudeResponse;
  }
}
