import { BaseAgent, BaseAgentConfig, AgentCommandConfig } from "./base";
import {
  CodexConfig,
  CodexResponse,
  CodexStreamCallbacks,
  Conversation,
} from "../types";

export class CodexAgent extends BaseAgent {
  private openaiApiKey: string;
  private model?: string;

  constructor(config: CodexConfig) {
    const baseConfig: BaseAgentConfig = {
      githubToken: config.githubToken,
      repoUrl: config.repoUrl,
      e2bApiKey: config.e2bApiKey,
      e2bTemplateId: config.e2bTemplateId,
      sandboxId: config.sandboxId,
      telemetry: config.telemetry,
    };

    super(baseConfig);
    this.openaiApiKey = config.openaiApiKey;
    this.model = config.model;
  }

  protected getCommandConfig(
    prompt: string,
    mode?: "ask" | "code"
  ): AgentCommandConfig {
    let instruction: string;
    if (mode === "ask") {
      instruction =
        "Research the repository and answer the user's questions. " +
        "Do NOT make any changes to any files in the repository.";
    } else {
      instruction =
        "Do the necessary changes to the codebase based on the users input.\n" +
        "Don't ask any follow up questions.";
    }

    let _prompt = `${instruction}\n\nUser: ${prompt}`;

    return {
      command: `codex --approval-mode auto-edit${
        this.model ? ` -m ${this.model}` : ""
      } --quiet "${_prompt}"`,
      errorPrefix: "Codex",
      labelName: "codex",
      labelColor: "ededed",
      labelDescription: "Pull requests generated by Codex agent",
    };
  }

  protected getDefaultTemplate(): string {
    return "vibekit-codex";
  }

  protected getEnvironmentVariables(): Record<string, string> {
    return {
      OPENAI_API_KEY: this.openaiApiKey,
    };
  }

  protected getApiKey(): string {
    return this.openaiApiKey;
  }

  protected getAgentType(): "codex" | "claude" {
    return "codex";
  }

  // Override generateCode to support history in the prompt
  public async generateCode(
    prompt: string,
    mode?: "ask" | "code",
    history?: Conversation[],
    callbacks?: CodexStreamCallbacks
  ): Promise<CodexResponse> {
    let instruction: string;
    if (mode === "ask") {
      instruction =
        "Research the repository and answer the user's questions. " +
        "Do NOT make any changes to any files in the repository.";
    } else {
      instruction =
        "Do the necessary changes to the codebase based on the users input.\n" +
        "Don't ask any follow up questions.";
    }

    let _prompt = `${instruction}\n\nUser: ${prompt}`;

    if (history) {
      _prompt += `\n\nConversation history: ${history
        .map((h) => `${h.role}\n ${h.content}`)
        .join("\n\n")}`;
    }

    // Override the command config with history-aware prompt
    const originalGetCommandConfig = this.getCommandConfig.bind(this);
    this.getCommandConfig = (p: string, m?: "ask" | "code") => ({
      ...originalGetCommandConfig(p, m),
      command: `codex --approval-mode auto-edit${
        this.model ? ` -m ${this.model}` : ""
      } --quiet "${_prompt}"`,
    });

    const result = await super.generateCode(prompt, mode, history, callbacks);

    // Restore original method
    this.getCommandConfig = originalGetCommandConfig;

    return result as CodexResponse;
  }
}
