/**
 * Calls the Devin agent to generate code based on a prompt
 * @param prompt - The text prompt describing the code to generate
 * @param apiKey - API key for accessing the Devin service
 * @returns A promise that resolves to the generated code response
 */
export async function callDevin(
  prompt: string,
  apiKey: string
): Promise<{ code: string }> {
  try {
    // In a real implementation, this would make an API call to Devin
    console.log(`Generating code with prompt: ${prompt}`);
    console.log(`Using Devin API key: ${apiKey.substring(0, 7)}...`);

    // Simulate API call delay
    await new Promise((resolve) => setTimeout(resolve, 500));

    // Return a mock response for this simple example
    return {
      code: `// Generated code based on: ${prompt}\nconsole.log("This is code generated by Devin");`,
    };
  } catch (error) {
    console.error("Error calling Devin:", error);
    throw new Error(
      `Failed to generate code: ${
        error instanceof Error ? error.message : String(error)
      }`
    );
  }
}
